import { Store, Product } from "./types";

export const stores: Store[] = [
  {
    id: "store-1",
    name: "Central Station Shop",
    description: "Sports and athletic wear for all levels, from beginner to professional athletes.",
    category: "Sports",
    latitude: 52.0894,
    longitude: 5.1101,
    address: "Stationshal 1, 3511 CE Utrecht",
    image_url: "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=400",
    opening_hours: "Mon-Sat 9:00-21:00, Sun 12:00-18:00",
    owner_id: null,
  },
  {
    id: "store-2",
    name: "Old Town Boutique",
    description: "Curated fashion and accessories in the heart of historic Utrecht.",
    category: "Fashion",
    latitude: 52.0912,
    longitude: 5.1184,
    address: "Oudegracht 120, 3511 AX Utrecht",
    image_url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400",
    opening_hours: "Mon-Sat 10:00-18:00, Sun 12:00-17:00",
    owner_id: null,
  },
  {
    id: "store-3",
    name: "University District Shop",
    description: "Everything students need — from stationery to tech accessories.",
    category: "Books",
    latitude: 52.0853,
    longitude: 5.1267,
    address: "Drift 23, 3512 BR Utrecht",
    image_url: "https://images.unsplash.com/photo-1596275281743-e7399c7bdfa9?w=400",
    opening_hours: "Mon-Fri 8:00-20:00, Sat 10:00-18:00",
    owner_id: null,
  },
  {
    id: "store-4",
    name: "Leidsche Rijn Outlet",
    description: "Brand outlets and sportswear at discounted prices.",
    category: "Sports",
    latitude: 52.0988,
    longitude: 5.0645,
    address: "Vleuterweide 50, 3452 Utrecht",
    image_url: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400",
    opening_hours: "Mon-Sat 10:00-20:00, Sun 12:00-18:00",
    owner_id: null,
  },
  {
    id: "store-5",
    name: "De Meern Fashion Center",
    description: "High-end fashion and luxury brands for the discerning shopper.",
    category: "Fashion",
    latitude: 52.0815,
    longitude: 5.0389,
    address: "Mereveldplein 1, 3454 Utrecht",
    image_url: "https://images.unsplash.com/photo-1604176354204-9268737828e4?w=400",
    opening_hours: "Mon-Sat 10:00-18:00",
    owner_id: null,
  },
  {
    id: "store-6",
    name: "Overvecht Shopping Hub",
    description: "Family fashion and kids clothing at affordable prices.",
    category: "Fashion",
    latitude: 52.1089,
    longitude: 5.1234,
    address: "Overkapel 2, 3561 Utrecht",
    image_url: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=400",
    opening_hours: "Mon-Sat 9:00-18:00",
    owner_id: null,
  },
  {
    id: "store-7",
    name: "Lombok Market",
    description: "Handmade jewelry, local accessories, and artisan crafts.",
    category: "Vintage",
    latitude: 52.0901,
    longitude: 5.1050,
    address: "Kanaalstraat 85, 3531 Utrecht",
    image_url: "https://images.unsplash.com/photo-1445053023192-8d45cb66099d?w=400",
    opening_hours: "Tue-Sat 10:00-18:00",
    owner_id: null,
  },
  {
    id: "store-8",
    name: "Kanaleneiland Tech",
    description: "Electronics, gadgets, and tech accessories for every budget.",
    category: "Electronics",
    latitude: 52.0734,
    longitude: 5.0987,
    address: "Columbuslaan 350, 3526 Utrecht",
    image_url: "https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=400",
    opening_hours: "Mon-Sat 10:00-20:00, Sun 12:00-17:00",
    owner_id: null,
  },
  {
    id: "store-9",
    name: "Science Park Books",
    description: "Academic books, professional supplies, and study materials.",
    category: "Books",
    latitude: 52.0856,
    longitude: 5.1678,
    address: "Padualaan 8, 3584 Utrecht",
    image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400",
    opening_hours: "Mon-Fri 8:00-21:00, Sat 10:00-17:00",
    owner_id: null,
  },
  {
    id: "store-10",
    name: "Oudwijk Vintage",
    description: "Vintage and classic fashion pieces, carefully curated secondhand.",
    category: "Vintage",
    latitude: 52.0878,
    longitude: 5.1345,
    address: "Oudwijkerdwarsstraat 12, 3581 Utrecht",
    image_url: "https://images.unsplash.com/photo-1551232864-3f0890e580d9?w=400",
    opening_hours: "Wed-Sat 11:00-18:00, Sun 12:00-17:00",
    owner_id: null,
  },
];

export const products: Product[] = [
  // Central Station Shop (Sports)
  { id: "prod-1", store_id: "store-1", name: "Running Shoes Nike Air", description: "Lightweight running shoes", category: "Footwear", price: 129.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-2", store_id: "store-1", name: "Adidas Training Shorts", description: "Breathable athletic shorts", category: "Clothing", price: 34.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-3", store_id: "store-1", name: "Yoga Mat Premium", description: "Non-slip exercise mat", category: "Equipment", price: 49.99, in_stock: false, image_url: "", updated_at: "2026-06-28" },
  { id: "prod-4", store_id: "store-1", name: "Protein Shaker Bottle", description: "700ml leak-proof shaker", category: "Accessories", price: 12.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-5", store_id: "store-1", name: "Resistance Bands Set", description: "5 different resistance levels", category: "Equipment", price: 24.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },

  // Old Town Boutique (Fashion)
  { id: "prod-6", store_id: "store-2", name: "Linen Summer Dress", description: "Light blue linen dress", category: "Dresses", price: 89.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-7", store_id: "store-2", name: "Leather Crossbody Bag", description: "Italian leather, tan", category: "Bags", price: 149.99, in_stock: true, image_url: "", updated_at: "2026-06-30" },
  { id: "prod-8", store_id: "store-2", name: "Silk Scarf Floral", description: "Hand-printed silk scarf", category: "Accessories", price: 59.99, in_stock: false, image_url: "", updated_at: "2026-06-25" },
  { id: "prod-9", store_id: "store-2", name: "Wool Blazer Navy", description: "Tailored wool blend blazer", category: "Outerwear", price: 199.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-10", store_id: "store-2", name: "Gold Hoop Earrings", description: "14k gold plated hoops", category: "Jewelry", price: 39.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },

  // University District Shop (Books)
  { id: "prod-11", store_id: "store-3", name: "Moleskine Notebook A5", description: "Classic hardcover ruled", category: "Stationery", price: 19.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-12", store_id: "store-3", name: "Scientific Calculator", description: "Casio FX-991EX", category: "Electronics", price: 29.99, in_stock: true, image_url: "", updated_at: "2026-06-29" },
  { id: "prod-13", store_id: "store-3", name: "USB-C Hub 7-in-1", description: "HDMI, USB3, SD card", category: "Electronics", price: 44.99, in_stock: false, image_url: "", updated_at: "2026-06-20" },
  { id: "prod-14", store_id: "store-3", name: "Highlighter Set 6-Pack", description: "Pastel colors, no bleed", category: "Stationery", price: 8.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-15", store_id: "store-3", name: "Laptop Stand Aluminum", description: "Adjustable ergonomic stand", category: "Accessories", price: 39.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },

  // Leidsche Rijn Outlet (Sports)
  { id: "prod-16", store_id: "store-4", name: "Puma Running Jacket", description: "Windproof lightweight jacket", category: "Clothing", price: 59.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-17", store_id: "store-4", name: "Football Boots Predator", description: "Adidas Predator Edge", category: "Footwear", price: 89.99, in_stock: false, image_url: "", updated_at: "2026-06-27" },
  { id: "prod-18", store_id: "store-4", name: "Swimming Goggles Pro", description: "Anti-fog, UV protection", category: "Equipment", price: 22.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-19", store_id: "store-4", name: "Cycling Gloves", description: "Padded half-finger gloves", category: "Accessories", price: 19.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-20", store_id: "store-4", name: "Dumbbell Set 20kg", description: "Adjustable vinyl dumbbells", category: "Equipment", price: 69.99, in_stock: true, image_url: "", updated_at: "2026-06-30" },

  // De Meern Fashion Center (Fashion)
  { id: "prod-21", store_id: "store-5", name: "Cashmere Sweater", description: "Pure cashmere, cream", category: "Knitwear", price: 249.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-22", store_id: "store-5", name: "Designer Sunglasses", description: "Ray-Ban Wayfarer Classic", category: "Accessories", price: 159.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-23", store_id: "store-5", name: "Tailored Trousers", description: "Slim fit, charcoal wool", category: "Trousers", price: 129.99, in_stock: false, image_url: "", updated_at: "2026-06-22" },
  { id: "prod-24", store_id: "store-5", name: "Leather Belt Italian", description: "Full grain leather", category: "Accessories", price: 79.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-25", store_id: "store-5", name: "Silk Tie Collection", description: "Set of 3 patterned ties", category: "Accessories", price: 89.99, in_stock: true, image_url: "", updated_at: "2026-06-30" },

  // Overvecht Shopping Hub (Fashion)
  { id: "prod-26", store_id: "store-6", name: "Kids Raincoat Yellow", description: "Waterproof, ages 4-8", category: "Kids", price: 29.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-27", store_id: "store-6", name: "Family Pack T-Shirts", description: "5 basic cotton tees", category: "Basics", price: 39.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-28", store_id: "store-6", name: "Denim Jeans Regular", description: "Classic fit, dark wash", category: "Jeans", price: 49.99, in_stock: true, image_url: "", updated_at: "2026-06-30" },
  { id: "prod-29", store_id: "store-6", name: "Winter Boots Kids", description: "Insulated, waterproof", category: "Kids", price: 44.99, in_stock: false, image_url: "", updated_at: "2026-06-15" },
  { id: "prod-30", store_id: "store-6", name: "Canvas Sneakers", description: "Unisex, multiple colors", category: "Footwear", price: 34.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },

  // Lombok Market (Vintage)
  { id: "prod-31", store_id: "store-7", name: "Handmade Silver Ring", description: "Artisan sterling silver", category: "Jewelry", price: 45.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-32", store_id: "store-7", name: "Macramé Wall Hanging", description: "Handwoven cotton", category: "Home Decor", price: 35.99, in_stock: true, image_url: "", updated_at: "2026-06-28" },
  { id: "prod-33", store_id: "store-7", name: "Ceramic Earrings Set", description: "Hand-painted, unique", category: "Jewelry", price: 24.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-34", store_id: "store-7", name: "Vintage Leather Journal", description: "Refillable, A5 size", category: "Stationery", price: 29.99, in_stock: false, image_url: "", updated_at: "2026-06-20" },
  { id: "prod-35", store_id: "store-7", name: "Woven Basket Bag", description: "Summer rattan bag", category: "Bags", price: 55.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },

  // Kanaleneiland Tech (Electronics)
  { id: "prod-36", store_id: "store-8", name: "Wireless Earbuds Pro", description: "ANC, 30hr battery", category: "Audio", price: 79.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-37", store_id: "store-8", name: "Mechanical Keyboard", description: "RGB, Cherry MX Blue", category: "Peripherals", price: 99.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-38", store_id: "store-8", name: "Portable Charger 20000mAh", description: "Fast charge, USB-C", category: "Accessories", price: 39.99, in_stock: true, image_url: "", updated_at: "2026-06-30" },
  { id: "prod-39", store_id: "store-8", name: "Webcam 4K", description: "Auto-focus, built-in mic", category: "Peripherals", price: 69.99, in_stock: false, image_url: "", updated_at: "2026-06-18" },
  { id: "prod-40", store_id: "store-8", name: "Smart Watch Fitness", description: "Heart rate, GPS, waterproof", category: "Wearables", price: 149.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },

  // Science Park Books (Books)
  { id: "prod-41", store_id: "store-9", name: "Introduction to Algorithms", description: "Cormen et al., 4th edition", category: "Textbooks", price: 69.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-42", store_id: "store-9", name: "Lab Notebook Grid", description: "200 pages, hardcover", category: "Stationery", price: 14.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-43", store_id: "store-9", name: "Anatomy Atlas", description: "Netter's, 8th edition", category: "Textbooks", price: 84.99, in_stock: false, image_url: "", updated_at: "2026-06-25" },
  { id: "prod-44", store_id: "store-9", name: "Whiteboard Markers Set", description: "8 colors, dry erase", category: "Stationery", price: 11.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-45", store_id: "store-9", name: "Ergonomic Mouse", description: "Vertical design, wireless", category: "Electronics", price: 34.99, in_stock: true, image_url: "", updated_at: "2026-06-29" },

  // Oudwijk Vintage (Vintage)
  { id: "prod-46", store_id: "store-10", name: "70s Denim Jacket", description: "Original Levi's, restored", category: "Outerwear", price: 89.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
  { id: "prod-47", store_id: "store-10", name: "Vintage Band T-Shirt", description: "Original 80s concert tee", category: "Tops", price: 49.99, in_stock: true, image_url: "", updated_at: "2026-07-01" },
  { id: "prod-48", store_id: "store-10", name: "Retro Polaroid Camera", description: "Refurbished, working", category: "Accessories", price: 119.99, in_stock: false, image_url: "", updated_at: "2026-06-20" },
  { id: "prod-49", store_id: "store-10", name: "Vintage Wool Coat", description: "1960s camel coat, M", category: "Outerwear", price: 129.99, in_stock: true, image_url: "", updated_at: "2026-06-30" },
  { id: "prod-50", store_id: "store-10", name: "Antique Pocket Watch", description: "Swiss movement, 1920s", category: "Accessories", price: 199.99, in_stock: true, image_url: "", updated_at: "2026-07-02" },
];
